/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:242398b8-ef80-4dfe-8386-09f1b6400ed9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_uYokr6012",
    "aws_user_pools_web_client_id": "3qkt1ktl1d3fnsthg1c049vng7",
    "oauth": {}
};


export default awsmobile; 
